# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirstAutomotive' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FirstAutomotive

  pod 'MBProgressHUD'
  pod 'AFNetworking'
  pod 'MJRefresh'
  pod 'Bugly'
  pod 'IQKeyboardManager'
  pod 'TTTAttributedLabel'
  pod 'DZNEmptyDataSet'

end
